name: NodeJS with Webpack

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn install
        yarn build

    - name: Push Build
      run: |
        git config --global user.email "c-warnick@users.noreply.github.com"
        git config --global user.name "Fluffy Palm"

        git add docs/**
        git commit -m "Build push"
        git push 
    
